### ISSUE TITLE
blobs not accessible

### ISSUE THREAD

**Issue by rwst** [robertwb/sage-patchbot#15]
Around 5-10% of male humans suffer from some form of color vision deficiency (see https://en.wikipedia.org/wiki/Color_blindness#Epidemiology). For them, greenish and orange/brown/reddish blobs are indistinguishable. Also, the blobs appear in high number on the web page, and color is not the best way to get a quick overview of such data, even for the other 90%.

This ticket is resolved when at least a second way to distinguish blobs is implemented, for example by changing the shape of blobs. Alternatively, use unique colors with different brightness (white/yellow/red/blue/black), or even just shades of gray.

This problem is well known to any good software engineer and treated thoroughly at 
https://en.wikipedia.org/wiki/Web_accessibility
http://www.w3.org/WAI/
https://www.google.de/#q=accessible+color+scheme

**Comment by fchapoton** [comment]
Here is a proposal:










![icones](https://cloud.githubusercontent.com/assets/5454848/6771576/0a3cabba-d0e2-11e4-9c96-bcc4603b2748.png)

I am not sure Zzz is universally understand as meaning "sleep". Maybe the moon crescent is better ?

Comments ?

**Comment by rwst** [comment]
Very nice. The moon would fit with pending, imho.

**Comment by fchapoton** [comment]
Well, *Pending* means that one bot is currently working on the ticket. So the sandhour seems better to me, with the meaning "please wait".

**Comment by fchapoton** [comment]
ok, the new icon set is now being used all over the place.
