### ISSUE TITLE
server: most ticket 0 blobs have wrong color after 5.13.beta3

### ISSUE THREAD

**Issue by rwst** [robertwb/sage-patchbot#39]
The page http://patchbot.sagemath.org/ and all pages of form http://patchbot.sagemath.org/?base=xyz show first the list of blobs summarizing results of ticket 0 runs. The wrong blobs are displayed in that any PluginFail of a previous version somehow leads to PluginFail in later versions, regardless if there later was a PluginFail. In fact, all versions after 5.13.beta2 except 6.1.1 show a PluginFail which certainly isn't right.

**Comment by fchapoton** [comment]
At least partially solved. There remains to decide whether to show the best or the worse result..
