### ISSUE TITLE
ignore invalid/dupe/wontfix tickets

### ISSUE THREAD

**Issue by rwst** [robertwb/sage-patchbot#48]
patchbot tries to test such tickets at the moment, see http://patchbot.sagemath.org/ticket/16591/

there isn't even code in there!

**Comment by jakobkroeker** [comment]
-close ticket?

-what if  ['milestone']  string  'sage-duplicate/invalid/wontfix' will be changed in future?
Is it possible to catch that issue (e.g. by having a checklist for changing  template milestone descriptions with an entry 'please update patchbot, too') ?

**Comment by fchapoton** [comment]
Currently:

    if not(ticket['status'] in ('needs_review', 'positive_review',
                                    'needs_info', 'needs_work')):
            if verbose:
                print('only test needs_* or positive_review tickets')
            return

So I think this can be closed.
