### ISSUE TITLE
patchbot fails to parse some tickets correctly

### ISSUE THREAD

**Issue by jakobkroeker** [robertwb/sage-patchbot#58]
patchbot fails to parse some tickets correctly, see

http://patchbot.sagemath.org/ticket/7660/

**Comment by fchapoton** [comment]
That is because there are some confusing TAB in the ticket description. We use TAB separated tsv file to get the ticket fields..

**Comment by fchapoton** [comment]
The channel from trac to patchbot is now through the xmlrpc interface of trac, and there is no longer any problem with TABs.

**Comment by jakobkroeker** [comment]
Thanks!
