### ISSUE TITLE
plugin.non_ascii: honor utf-8 coding declaration

### ISSUE THREAD

**Issue by nthiery** [robertwb/sage-patchbot#65]
Currently, the non_ascii plugin complains when a utf-8 character is found in the diff, even when the containing file is declared as being utf-8 coded with a header `# -*- coding: utf-8 -*-`.

See e.g. http://patchbot.sagemath.org/log/6484/Gentoo%20Base%20System/2.2/x86_64/3.2.1-gentoo-r2/sage4/2015-05-05%2006:06:45%20+0200?plugin=plugins.non_ascii.

**Comment by fchapoton** [comment]
This should be better now. The non_ascii plugin will now only look for unicode characters in .py and .pyx files, at the condition that they are missing the utf8 declaration.

**Comment by nthiery** [comment]
On Mon, Jul 27, 2015 at 12:12:00PM -0700, fchapoton wrote:
>    This should be better now. The non_ascii plugin will now only look for
>    unicode characters in .py and .pyx files, at the condition that they
>    are missing the utf8 declaration.

Thank you!!!

				Nicolas
--
Nicolas M. Thiéry "Isil" <nthiery@users.sf.net>
http://Nicolas.Thiery.name/
