### ISSUE TITLE
not all tickets without code are ignored on web pages

### ISSUE THREAD

**Issue by rwst** [robertwb/sage-patchbot#69]
http://trac.sagemath.org/ticket/16721
is a wontfix ticket that still appears in the patchbot page and has a status page:
http://patchbot.sagemath.org/ticket/16721/

**Comment by fchapoton** [comment]
Done. Tickets with duplicate/invalid/wontfix status do no longer appear in the ticket lists.

**Comment by rwst** [comment]
Thanks. The pages look much better now, BTW.
