### ISSUE TITLE
a bug in startup_modules plugin?

### ISSUE THREAD

**Issue by dimpase** [robertwb/sage-patchbot#71]
On #18997 (http://patchbot.sagemath.org/ticket/18997/) I saw PluginFailed - on startup_modules, which appears to be caused by innocent things like

       from itertools import combinations

The patchbots seem to think that "sage.combinat.designs.itertools" is a valid module name, see e.g.
http://patchbot.sagemath.org/ticket/18997/plugin/plugins.startup_modules/2015-08-26%2006:41:06%20+0000/

**Comment by videlec** [comment]
See also http://patchbot.sagemath.org/ticket/18411/

**Comment by fchapoton** [comment]
This is a bug in sage. A call to

    print '\n'.join(sorted(sys.modules.keys()))

gives many wrong module names, such as sage.misc.__builtin__ or sage.misc.__future__

**Comment by fchapoton** [comment]
This is solved in patchbot 2.5.7, which has a better handling of the startup module.
