### ISSUE TITLE
Spurious error report from plugin doctest_continuation

### ISSUE THREAD

**Issue by egourgoulhon** [robertwb/sage-patchbot#74]
Hi, 
Having a docstring line starting by "..." triggers a failed plugins.doctest_continuation, even if the line is part of some regular sentence and not part of any doctest. See 
https://groups.google.com/d/msg/sage-devel/2Trrp-HTk8k/d-NNENZ_AQAJ
for an example.

**Comment by fchapoton** [comment]
in this case, just ignore the advice of the patchbot.
