### ISSUE TITLE
Add a --owner option

### ISSUE THREAD

**Issue by nthiery** [robertwb/sage-patchbot#77]
Currently the patchbot reports only mention the machine name. So we need to maintain and lookup a separate wiki page [1] which maps those machine names to patchbot owners. It would be simpler to have a --owner option so that those owners c/should run the patchbot as:

    sage -patchbot --owner "Nicolas M. Thiéry <nthiery@users.sf.net>"

[1] http://wiki.sagemath.org/buildbot/owners

**Comment by fchapoton** [comment]
This option has been added to patchbot 2.5.4, see http://trac.sagemath.org/ticket/20313

**Comment by nthiery** [comment]
For the record, this is: 6eb08e0
Thank you Frédéric! I'll try this out tomorrow.
